# Generated by Django 5.0.6 on 2024-06-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_article_image'),
        ('users', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='info.vacancy'),
            preserve_default=False,
        ),
    ]
