# Generated by Django 5.0.6 on 2024-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_car_production_year_remove_car_vin_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
