# Generated by Django 5.0.6 on 2024-06-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_coupon_alter_parkingspace_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponclient',
            old_name='user',
            new_name='client',
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.couponclient'),
        ),
    ]
