# Generated by Django 5.0.6 on 2024-06-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_rename_user_couponclient_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='client',
            new_name='clients',
        ),
    ]
