# Generated by Django 5.0.6 on 2024-06-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_accrual_bank_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
