# Generated by Django 5.0.6 on 2024-10-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/company/logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='website_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
