# Generated by Django 5.0.6 on 2024-10-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_company_logo_company_website_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='title',
            new_name='name',
        ),
    ]
