# Generated by Django 5.0.6 on 2024-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_companyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
