# Generated by Django 5.0.6 on 2024-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='production_year',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin',
        ),
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
