# Generated by Django 5.0.6 on 2024-06-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_accrual_parkingspace_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspace',
            old_name='number_parking_space',
            new_name='number',
        ),
    ]
