# Generated by Django 5.0.6 on 2024-06-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_rename_number_parking_space_parkingspace_number'),
        ('users', '0003_employee_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('amount', 'Сумма')], max_length=10)),
                ('discount_value', models.FloatField()),
                ('min_amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/parking_spaces'),
        ),
        migrations.CreateModel(
            name='CouponClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='client',
            field=models.ManyToManyField(related_name='coupons', through='system.CouponClient', to='users.client'),
        ),
    ]
