# Generated by Django 5.0.6 on 2024-06-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrual',
            name='bank_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.bankcard'),
        ),
    ]
