# Generated by Django 5.0.6 on 2024-06-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_article_image'),
        ('users', '0003_employee_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.client')),
                ('grade', models.IntegerField()),
                ('body', models.TextField()),
            ],
        ),
    ]
